### P8.深度理解`nn.CrossEntropyLoss`

In [14]:
import torch
from torch import nn

torch.manual_seed(0)

In [15]:
loss = nn.CrossEntropyLoss()

input = torch.randn(3, 5, requires_grad=True)
input

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845],
        [-1.3986,  0.4033,  0.8380, -0.7193, -0.4033],
        [-0.5966,  0.1820, -0.8567,  1.1006, -1.0712]], requires_grad=True)

这里的(3, 5)表示有3个样本，是一个5分类的任务，其具体的值如上所示。

In [8]:
target = torch.empty(3, dtype=torch.long).random_(5)
target

tensor([3, 0, 0])

In [9]:
loss(input, target)

tensor(2.2729, grad_fn=<NllLossBackward0>)

具体计算过程如下

In [10]:
# 1. 对(3, 5)的行，进行softmax，按行进行累加结果为1
softmax = nn.Softmax(dim=1)
softmax(input)

tensor([[0.6118, 0.0977, 0.0148, 0.2313, 0.0443],
        [0.0474, 0.2873, 0.4437, 0.0935, 0.1282],
        [0.0997, 0.2172, 0.0769, 0.5442, 0.0620]], grad_fn=<SoftmaxBackward0>)

In [11]:
# 2. 对softmax后的值进行取对数
torch.log(softmax(input))

tensor([[-0.4913, -2.3257, -4.2111, -1.4639, -3.1168],
        [-3.0493, -1.2474, -0.8127, -2.3700, -2.0541],
        [-2.3056, -1.5270, -2.5657, -0.6084, -2.7802]], grad_fn=<LogBackward0>)

In [13]:
# 3.将对应的target相加，取平均然后再取负数：
-((-1.4639) + (-3.0493) + (-2.3056)) / 3

2.2729333333333335

发现结果是一致的